### ISSUE TITLE
Feature: Recently used directory

### ISSUE THREAD

**Issue by fixnil** [KristofferStrube/Blazor.FileSystemAccess#17]
Hello,

Thanks for your great effort!

I'm working on something interesting with your project, but I'm having a problem right now.

I want to get the recently used path or save the Handle, but I can't find the corresponding API. Is there any way?

Thanks again for your dedication!

**Comment by KristofferStrube** [comment]
Hey @fixnil,

Thanks for your interest in the project. 😊

[This article](https://web.dev/file-system-access/) talks about the API in general.
They also present [this sample app](https://googlechromelabs.github.io/text-editor/) that handles a list of recently opened files.

They keep track of the files using IndexedDB which can keep key-value pairs without serializing like in LocalStorage.

Hope that helps your search.
