### ISSUE TITLE
Bug: The option StartIn is invalid

### ISSUE THREAD

**Issue by fixnil** [KristofferStrube/Blazor.FileSystemAccess#24]
Hi @KristofferStrube,

There is bad news and good news here 😃

The bad news is that StartIn is invalid, because the new keyword makes it impossible to get the data covered by the child class in the parent class.

The good news is that I fixed the issue and submitted a PR.

**Comment by fixnil** [comment]
Also, I noticed that some async method signatures are optimized.
Can a patch version be released, I want to apply the changes asap.

**Comment by KristofferStrube** [comment]
Thanks for the fix. I see that my refactoring of these option classes were a bit too harsh. Had thought the base class method would use the property of the derived class but I see your solution fixes this. I will merge and make a Nuget release with this and the Async naming fixes in a bit.

**Comment by fixnil** [comment]
Excellent! I have updated to the latest version and everything is normal 👏 

Thanks!
