### ISSUE TITLE
Support URL.createObjectURL

### ISSUE THREAD

**Issue by JasonKoopmans** [KristofferStrube/Blazor.FileSystemAccess#26]
https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL

Implementing this API permits the creation of browser addressable urls for `File` and `Blob`.  

These examples provide some tangible use cases.

https://developer.mozilla.org/en-US/docs/Web/API/File_API/Using_files_from_web_applications#example_using_object_urls_to_display_pdf

A drag is the need to also implement `URL.revokeObjectURL` which deallocates a url resource to refer to the object.  
https://developer.mozilla.org/en-US/docs/Web/API/URL/revokeObjectURL

**Comment by KristofferStrube** [comment]
Hey @JasonKoopmans,

That sounds interesting. Especially how that relates to the lifetime of the reference to it. It is the plan to implement the entire [File API](https://www.w3.org/TR/FileAPI/) in which these methods are defined. I will ensure that I update you when that is accomplished. 🙂

**Comment by KristofferStrube** [comment]
An update on this is that I have started the development of the FileAPI wrapper as its own project. Once that is more featureful and published to Nuget this package will be updated to use it.
https://github.com/KristofferStrube/Blazor.FileAPI

**Comment by KristofferStrube** [comment]
This was fixed as a part of #28 and has been published in version 2.0.0 to NuGet.

From the [Blazor.FileAPI](https://github.com/KristofferStrube/Blazor.FileAPI) you can use the [URLSerivce](https://github.com/KristofferStrube/Blazor.FileAPI#add-to-service-collection) to call `CreateObjectURLAsync` on some `Blob`.
