### ISSUE TITLE
question: random access (seeking?)

### ISSUE THREAD

**Issue by aloneguid** [KristofferStrube/Blazor.FileSystemAccess#37]
Thanks for the great library by the way.
I have an issue where I'm trying to get a small amount of data from a very large file on disk (wasm application). Is it possible to seek inside the file without re-reading all the data from start?

**Comment by KristofferStrube** [comment]
Hey @aloneguid,
Glad that you appreciate the library.

It is an interesting question. This is actually more related to my [Blazor File API library](https://github.com/KristofferStrube/Blazor.FileAPI) which this library depends on.

When we read a file we use [Blazor.FileAPI](https://github.com/KristofferStrube/Blazor.FileAPI). I can't remember if getting the `File` loads the entire file into memory, but my guess would be that it is only a reference. If it is only a reference then we can use the `Slice` method to get a specific section as we see in [this sample](https://kristofferstrube.github.io/Blazor.FileAPI/Slice).

I will try to check this myself to see if the solution is performant for files on the disc (check whether or not we can slice files from the disc without reading it all).

**Comment by aloneguid** [comment]
Thanks @KristofferStrube. I've made an early prototype using `slice` and it seems to work. I think this can be optimised somehow but works much faster than `IBrowserFile` with read skipping. I can raise a PR for this if you like.

**Comment by aloneguid** [comment]
btw i have to call `slice` every time `Read` is called, otherwise read will try to read more than i need and throw an exception, not sure it's by design.

**Comment by aloneguid** [comment]
Yes, but `ReadableStream` stream is forward only (not seekable) which is what I need ;)

**Comment by KristofferStrube** [comment]
Ah, cool I got you.
What would the PR entail?

**Comment by KristofferStrube** [comment]
Side comment: I saw you were using a file drop library in your project. This library will support that in the near future as well. ;)

**Comment by aloneguid** [comment]
just trying something here https://github.com/aloneguid/ironcompress/pull/13

**Comment by aloneguid** [comment]
Thank you :) Closing.

**Comment by lvde0** [comment]
Hey, are there still plans to merge a seekable Stream any time soon?

**Comment by KristofferStrube** [comment]
I would be very interested in implementing this in Blazor.FileAPI. I will create an issue there soon.

**Comment by lvde0** [comment]
@KristofferStrube Awesome! I am trying to read large (>1Gb) zip files, but `ZipArchive` can only deal with seekable and synchronous streams. So at least the seekable bit would be solved that way :)
