### ISSUE TITLE
NuGet and check API availability

### ISSUE THREAD

**Issue by Enfis** [KristofferStrube/Blazor.FileSystemAccess#4]
Hello Kristoffer, great wrapper!

Are you planning to add this wonderful library to NuGet?

An "isSupported" method will be great as well, I don't know exactly if some browsers will add partial support to this API later...

Thank you, best regards

**Comment by KristofferStrube** [comment]
Hey @Enfis 🙂

I plan to plublish to Nuget in next week.

Good idea with the `isSupported()` method. Will have to look into how that can be done.

**Comment by KristofferStrube** [comment]
Hey @Enfis,
I have added the `IsSupported()` method now.

**Comment by Enfis** [comment]
You did a great job!

Just a suggestion ... if you wish to add futher classes, like a wrapper for the .NET [```Stream```](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream?view=net-6.0) class, please leave "lower-levels" classes (like **FileSystemWritableFileStream**) public, don't make them private.

Cheers 😉👍

**Comment by KristofferStrube** [comment]
`FileSystemWritableFileStream` is public, with protected properties, but an internal constructor.

I think that should be fine for extensibility while still concealing the constructor that is not part of the API.

**Comment by KristofferStrube** [comment]
Hey @Enfis 
It is now on Nuget: https://www.nuget.org/packages/KristofferStrube.Blazor.FileSystemAccess/
😁
