### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by Sean4572435243** [KristofferStrube/Blazor.FileSystemAccess#40]
Is there a meaningful performance improvement moving up from version 2.1?  Or is 3+ a refactoring or code optimization effort?

**Comment by KristofferStrube** [comment]
The primary change from 2.1.0 to 3.0.0 and above is that it now uses the File System Blazor package to represent file handles after their definitions were moved to that API spec. Some bug fixes were found while constructing that package and some ease-of-use cases with regards to the ValuesAsync method of the DirectoryFileHandle.
