### ISSUE TITLE
Add support for OPFS (origin private file system)?

### ISSUE THREAD

**Issue by datvm** [KristofferStrube/Blazor.FileSystemAccess#41]
Do you have any plan for supporting [OPFS](https://developer.chrome.com/articles/origin-private-file-system/)? It's almost the same thing except users don't pick or see the files. The library already cover all the interop interfaces and we only need to add a call to [`navigator.storage.getDirectory()`](https://developer.mozilla.org/docs/Web/API/StorageManager/getDirectory).

**Comment by KristofferStrube** [comment]
It is not a part of this API since November last year but was originally also covered in this wrapper. Checkout https://github.com/KristofferStrube/Blazor.FileSystem where what you hint to is now wrapped.

**Comment by datvm** [comment]
Oops sorry somehow I missed it! Thanks 😅
