### ISSUE TITLE
CopyToAsync() can write too much

### ISSUE THREAD

**Issue by henk787** [KristofferStrube/Blazor.FileSystemAccess#42]
I am using the WritableStream like this:

```
await using var newFileHandle = await rootDirectory.GetFileHandleAsync(publicatie.FileName, new() { Create = true });
await using var newFile = await newFileHandle.CreateWritableAsync();                                                            
await memStream.CopyToAsync(newFile);      

```

and later I am reading that file back into a ZipArchive.   
While for most files this worked Ok, for some of the larger ones it resulted in  the Zip error  **End of Central Directory record could not be found.**

Debugging revealed that the stored file's Length was too long. It was the _Capacity_ of the original MemoryStream where it should have been the _Length_.  So the workaround I found is to use TruncateAsync with a known-good value. 

```
...
await memStream.CopyToAsync(newFile);                                        
await newFile.TruncateAsync((ulong) args.File.Size);

```

**Comment by KristofferStrube** [comment]
Hey @henk787 glad you are using the library and its associated libraries. 💪

This is probably not related directly to the code in this repository, but let's keep it here for now as it could be the [Blazor.FileSystem](https://github.com/KristofferStrube/Blazor.FileSystem) repository's `FileSystemWritableFileStream` that is the cause or its base class `WritableStream` from the [Blazor.Streams](https://github.com/KristofferStrube/Blazor.Streams/). I will look into this tomorrow.

If you can share a sample file that reproduces this error then that might help me in debugging the problem, but it is all okay if that isn't possible.

Thanks for reporting the problem. ❤

**Comment by KristofferStrube** [comment]
How do you construct the original `memStream`?

**Comment by henk787** [comment]
Below is a simple MRE.

The "Read" and "Written" WiteLines already show different values. 
The Zip is not really part of it but it will throw when fthe file is >~ 270k. 

```
@page "/"
@using KristofferStrube.Blazor.FileSystem;
@using System.IO.Compression;
@inject IStorageManagerServiceInProcess StorageManagerService

<InputFile Size="100" OnChange="a => OpenFile(a)" />
<p>@message</p>

@code {

    string fileName = "test.zip";
    string message;

    async Task OpenFile(InputFileChangeEventArgs args)
    {
        var rootDirectory = await StorageManagerService.GetOriginPrivateDirectoryAsync();
    
        // Save it
        using (var stream = args.File.OpenReadStream(50 * 1024 * 1024))
        {
            var memStream = new MemoryStream();
            await stream.CopyToAsync(memStream);
            await using var newFileHandle = await rootDirectory.GetFileHandleAsync(fileName, new() { Create = true });
            await using var newFile = await newFileHandle.CreateWritableAsync();
            memStream.Position = 0;
            await memStream.CopyToAsync(newFile);
            Console.WriteLine($"Written {memStream.Length}");
        }

        // Read it back
        await using (var fileHandle = await rootDirectory.GetFileHandleAsync(fileName))
        {
            await using var file = await fileHandle.GetFileAsync();
            var buffer = await file.ArrayBufferAsync();
            Console.WriteLine($"Read {buffer.Length}");
            var stream = new MemoryStream(buffer);
            using var archive = new ZipArchive(stream);
            message = $"Zip has {archive.Entries.Count} entries";
        }

    }
}

```

**Comment by henk787** [comment]
I found this piece in WriteablStream, hich is indeed part of your FileAPI package. 
 It looks like a likely cause:

```
public override async Task WriteAsync(byte[] buffer, int offset, int count, CancellationToken cancellationToken)
{
    await WriteAsync(buffer, cancellationToken);
}
```

I think that CopyAsync uses this for the last block. 
Now that I understand the issue there are multiple workarounds.

And before I forget, it is a very nice package. Glad I found it. 
It enables a whole new kind of static file and PWA apps.

**Comment by KristofferStrube** [comment]
Hey again @henk787,
I've tried out your sample and it reproduces the problem pretty well.
The method you pointed to from the `Blazor.Streams` package is not the one that gets called as a part of the `CopyAsync` method. It is [this method](https://github.com/KristofferStrube/Blazor.FileSystem/blob/main/src/KristofferStrube.Blazor.FileSystem/FileSystemWritableFileStream.cs#L23-L26) from the `Blazor.FileSystem` package that gets called:
```csharp
public override async ValueTask WriteAsync(ReadOnlyMemory<byte> buffer, CancellationToken cancellationToken = default)
{
    await JSReference.InvokeVoidAsync("write", buffer.ToArray());
}
```

I've tried debugging that method while running your sample and I found that it parsed a `ReadOnlyMemory` buffer that was too big. It gets this size directly from the source stream when it reads the first chunk. I've tried removing the `MemoryStream` that you copy to from the original `IBrowserFile` `Stream` and when I skip that step it works fine.

```csharp
@page "/"
@using KristofferStrube.Blazor.FileSystem;
@using System.IO.Compression;
@inject IStorageManagerServiceInProcess StorageManagerService

<InputFile Size="100" OnChange="a => OpenFile(a)" />
<p>@message</p>

@code {

    string fileName = "test.zip";
    string message;

    async Task OpenFile(InputFileChangeEventArgs args)
    {
        var rootDirectory = await StorageManagerService.GetOriginPrivateDirectoryAsync();
    
        // Save it
        using (var stream = args.File.OpenReadStream(50 * 1024 * 1024))
        {
            await using var newFileHandle = await rootDirectory.GetFileHandleAsync(fileName, new() { Create = true });
            await using var newFile = await newFileHandle.CreateWritableAsync();
            await stream.CopyToAsync(newFile);
            Console.WriteLine($"Written {stream.Length}");
        }

        // Read it back
        await using (var fileHandle = await rootDirectory.GetFileHandleAsync(fileName))
        {
            await using var file = await fileHandle.GetFileAsync();
            var buffer = await file.ArrayBufferAsync();
            Console.WriteLine($"Read {buffer.Length}");
            var stream = new MemoryStream(buffer);
            using var archive = new ZipArchive(stream);
            message = $"Zip has {archive.Entries.Count} entries";
        }

    }
}
```
This hints to me that this might be some problem with chaining streams which I will have to look into.

So to conclude I'm still looking into the cause of the problem, but I have not found an immediate fix for the problem.

**Comment by KristofferStrube** [comment]
Hey @henk787,

After looking more into it I don't think it's a problem with this library. I recommend that you **don't** write the stream to an intermediate `MemoryStream` like I have done in my last comment as this solves the problem in your given example.
