### ISSUE TITLE
Question: Is it possible to get a directory handle without using the directory picker?

### ISSUE THREAD

**Issue by mhsimkin** [KristofferStrube/Blazor.FileSystemAccess#44]
Hi:

I know the path to the directory that I need to open to look for a file.  Is there anyway to get a directory handle without using the directory picker?  For example: C:/Users/Public/AccountPictures/[SID].

If I know the path to a file, but the name will have a wildcard, would it be possible to open the file? All the files at the above path will have are names as [GUID]-Image[size], where the GUID would be the same for all the files in the directory.  I need to get access to [GUID]-Image96.jpg and [GUID]-Image64.jpg.

The full file path would be: C:/Users/Public/AccountPictures/[SID]/[GUID]-Image[size].jpg,

This is the location where the avatar images used on the Windows Logon Screen, Outlook, Teams, etc are stored.

Thanks

-marc

**Comment by KristofferStrube** [comment]
Hey @mhsimkin,

Without opening the file or directory picker, you can't access files or directories using the File System Access API. The reason why you can't do this is because it would be a security risk.

I hope you find some other solution for your project, though. 😊

**Comment by mhsimkin** [comment]
Thanks. That is what I figured.

**Comment by mhsimkin** [comment]
One other question. How can I open the file picker in a folder that is not well known? Thanks.

**Comment by KristofferStrube** [comment]
Hey @mhsimkin there is an overload for all the file/directory dialog methods without the extra option which you can use if you have no preferences.
